### ISSUE TITLE
What is the Nav component doing?

### ISSUE THREAD

**Issue by gabssnake** [vercel/next-react-server-components#48]
Hi everyone,

Thanks for sharing this demo!

I was looking at the [source of `Nav` component](https://github.com/vercel/next-react-server-components/blob/a873ad96ab4291c58c5c2299899df4114270af46/components/nav.js#L2):

```javascript
export default function Nav() {
  ;<ul className="nav-ul">
    <Item href="/newest">new</Item>
    ...

    <style jsx>{`
       ...
    `}</style>
  </ul>
}
```

Why is this component returning `undefined`? *What does it do* if nothing is being returned?
*How* does this have an effect on DOM, state, styles, or anything else?
Is this a common pattern? Where can I read more about this? I'm intrigued :)

**Comment by huozhi** [comment]
It was a clone of hacker news nav bar
<img width="474" alt="image" src="https://user-images.githubusercontent.com/4800338/181740089-c8ee1f6e-7fa1-445c-95cb-abd991a81738.png">

We hide it in the demo it's because that's not the major point of this demo. We don't want user to be distraced from the main content displaying. It's just not used. We'll clean it up later, thanks for noticing it

**Comment by gabssnake** [comment]
Thank you for answering.
I was afraid it a was a new horrible way of doing invisible things.
Turns out it does was it says :)

**Comment by leerob** [comment]
We brought back the nav when refactoring 😄 

https://next-rsc-hn.vercel.app/
